# Generated by Django 5.0.1 on 2024-03-04 16:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.IntegerField(default=None)),
                ('address', models.TextField()),
                ('product', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.action')),
            ],
        ),
    ]
