# Generated by Django 5.0.1 on 2024-03-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='action',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='api.action'),
        ),
    ]
