# Generated by Django 5.0.1 on 2024-03-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
            preserve_default=False,
        ),
    ]
