# Generated by Django 5.0.1 on 2024-03-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_checkout_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment',
            field=models.ForeignKey(default='Cash On Delivering', on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
    ]
