# Generated by Django 5.0.1 on 2024-03-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_checkout_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
