# Generated by Django 5.0.1 on 2024-03-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_checkout_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
