# Generated by Django 5.0.1 on 2024-03-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_checkout_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='action',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.action'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
    ]
