# Generated by Django 5.0.1 on 2024-03-15 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_checkout_user_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='action',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.CASCADE, to='api.action'),
        ),
    ]
