# Generated by Django 5.0.1 on 2024-03-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_checkout_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='action',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.action'),
        ),
    ]
